language: python
python:
- '2.7'

matrix:
  include:
    - env: TOXENV=flake8
    - env: TOXENV=markdown-link
      before_install: gem install mdl
    - env: TOXENV=linkchecker
install:
  - pip install -q -r requirements.txt
  - pip install tox
script: mkdocs build


# Deploy artifacts
after_success:
  - ./.travis.sh
