site_name: 1upkeyboards.com Docs
copyright: 2017-2018 &copy; Brian J King unless otherwise noted.
site_description: 1upkeyboards.com website documentation
site_author: Brian J King
repo_url: https://github.com/brianjking/1upkeyboard-docs
pages:
- Home: index.md
- WordPress Basics:
    - Adding News Posts: wordpress-basics/adding-news-posts.md
    - Updating The Menu: wordpress-basics/menu.md
    - Adding Media: wordpress-basics/media.md
    - Managing Pages: wordpress-basics/managing-pages.md
    - Manually Flush Siteground Caching: wordpress-basics/flush-cache.md
    - Keeping WordPress Core & Plugins Updated: wordpress-basics/update-plugins.md
    - Managing Homepage Slider: wordpress-basics/managing-homepage-slider.md
    - Divi Visual Page Builder: wordpress-basics/divi-visual-builder.md
    - Other Resources: wordpress-basics/other-resources.md
- WooCommerce:
    - Adding Products: woocommerce/add-products.md
    - Editing Products: woocommerce/edit-products.md
    - Packing & Shipping: woocommerce/packing-shipping.md
    - WooCommerce Reporting: woocommerce/woo-reporting.md
    - Upsells & Cross-sells: woocommerce/upsells-cross-sells.md
    - Coupons: woocommerce/woo-coupons.md
    - Categories: woocommerce/woo-categories.md
    - WooCommerce Shortcodes: woocommerce/woo-shortcodes.md
    - Misc WooCommerce: woocommerce/misc-woocommerce.md
- Advanced:
    - Hiding Elements on Certain Device Types with Divi: advanced/hide-elements-with-divi.md
    - A/B Testing with Divi: advanced/ab-testing-with-divi.md
    - Uploading HEX & JSON Files: advanced/managing-hex-json.md
# Configuration
theme:
  name: 'material'
  logo: 'images/1uplogo.svg'
  language: 'en'
  palette:
    primary: 'blue-grey'
    accent: 'light-blue'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'


# Options
extra:
  logo: 'images/download.svg'
  feature:
    tabs: false
  social:
    - type: globe
      link: https://brianjking.io
    - type: github-alt
      link: https://github.com/brianjking
    - type: twitter
      link: https://twitter.com/brianjking
    - type: linkedin
      link: https://www.linkedin.com/in/brianjking

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - fontawesome_markdown
